#!/bin/bash
# This script is intended to install dependencies needed for the app

# Update the package repository
sudo yum update -y

# Install Docker to run a containerized application
sudo yum install -y docker
sudo service docker start
sudo usermod -a -G docker ec2-user

# Make sure Docker starts on every system boot
sudo systemctl enable docker

# Any other dependency installations can be added here
