#!/bin/bash
# This script is intended to run the application

# Load the Docker image
docker build -t laylmah/final-python-ex2:2

# Run the Docker container
docker run -d -p 80:80 laylmah/final-python-ex2:2

# Optionally, add commands to wait for the application to fully start
# e.g., waiting for a specific log entry or listening on a port


