#!/bin/bash
sudo docker ps -a | grep final-python
EXITCODE=$?

if [ "$EXITCODE" -ne "0" ]; then
    echo "Container final-python not found."
    exit 1  # Non-zero exit code for error state
else
    sudo docker stop final-python
    sudo docker rm final-python
    echo "Container final-python stopped and removed successfully."
fi
